# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RayaWenderlichiOSPracticeProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RayaWenderlichiOSPracticeProj
  pod 'Kingfisher', '~> 7.0'

  target 'RayaWenderlichiOSPracticeProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RayaWenderlichiOSPracticeProjUITests' do
    # Pods for testing
  end

end
